title: "ArXiv AI Digest"
description: "매일 업데이트되는 최신 AI 논문 다이제스트"
baseurl: "/arxiv-ai-mailing"
url: "https://2shin0.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

collections:
  llm_papers:
    output: true
    permalink: /LLM/:name/
  all_papers:
    output: true
    permalink: /ALL/:name/

include:
  - LLM/
  - ALL/
  - digest/

exclude:
  - venv/
  - __pycache__/
  - "*.py"
  - "*.sh"
  - requirements.txt
  - .gitignore
  - .gitattributes
  - readme.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "LLM"
      type: "pages"
    values:
      layout: "default"
      category: "LLM"
  - scope:
      path: "ALL"
      type: "pages"
    values:
      layout: "default"
      category: "ALL"
